CREATE TABLE IF NOT EXISTS public.webhook_debug_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload jsonb,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);
